# Generated by Django 6.0.2 on 2026-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspapertitle',
            name='is_active',
        ),
        migrations.AddField(
            model_name='newspapertitle',
            name='status',
            field=models.CharField(choices=[('EXISTING', 'Existing Database Record'), ('PENDING', 'New Application'), ('REJECTED', 'Rejected Submission')], default='PENDING', max_length=20),
        ),
    ]
