# Generated by Django 6.0.2 on 2026-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_remove_newspapertitle_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspapertitle',
            name='title_text',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
