# Generated by Django 6.0.2 on 2026-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0003_alter_newspapertitle_title_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspapertitle',
            name='title_text',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
