# Generated by Django 6.0.2 on 2026-02-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0004_alter_newspapertitle_title_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspapertitle',
            name='status',
        ),
    ]
